### ISSUE TITLE
"How to run" instructions do not contain how to connect to sphere

### ISSUE THREAD

**Issue by schleichardt** [HTW-Projekt-2014-Commercetools/api#4]
Without the configuration it throws the following exception:

```
Missing: No configuration setting found for key 'sphere.project'
No source available, here is the exception stack trace:
->com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'sphere.project'
```

**Comment by MeiSign** [comment]
We should add additional documentation and a custom exception here that points to it.

**Comment by sasfeld** [comment]
Added guide. Please check.

**Comment by schleichardt** [comment]
* you could link the page to download JDK 8 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html (often people download by accident just the virtual machine)
* it is called SPHERE.IO
* in 3. it is API CLIENTS, not API ACCESS
