### ISSUE TITLE
Implement documentation endpoint

### ISSUE THREAD

**Issue by schleichardt** [HTW-Projekt-2014-Commercetools/api#5]
controllers.Documentation#showDocumentation

**Comment by peter-gerhard** [comment]
added redirect to readme.md for now

**Comment by MeiSign** [comment]
Wiki files should not be in the same folder with our API Sources. We could consider putting them in the ressources package but I think the wiki should be a separate project...

**Comment by sasfeld** [comment]
The advantage: Write once and deliver only the API documentation. By including the doc as Git submodule, we still have the repos separated. 
We could also deliver the complete README.MD - or fall back to a hardcoded and duplicated solution which I wanted to prevent.

Any opinions?

**Comment by MeiSign** [comment]
This issue was moved to neeedo/neeedo-api#6
