### ISSUE TITLE
Check JVM 8 compatibility at compilation and start

### ISSUE THREAD

**Issue by schleichardt** [HTW-Projekt-2014-Commercetools/api#8]
http://stackoverflow.com/questions/19208942/enforcing-java-version-for-scala-project-in-sbt/19618654#19618654 shows different possibilities to check/force the JDK 8 at compile time.

With system properties http://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html you can check at start the correct JVM version.

**Comment by peter-gerhard** [comment]
fixed
should be necessary for all projects using sphere.sdk here's a solution.
add to buildt.sbt:

      initialize := {
        val _ = initialize.value // run the previous initialization
        if (sys.props("java.specification.version") < "1.8") {
          sys.error("Java 8 is required for this project.")
        }
      }
